services:
  front-app:
    image: node:20
    container_name: vt_app
    working_dir: /app
    volumes:
      - ./front:/app
      - /app/node_modules
    ports:
      - "5120:5173"
    command: sh -c "npm install && npm run dev -- --host"
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    depends_on:
      - backend-spring

  backend-spring:
    image: openjdk:17
    container_name: spring_app
    working_dir: /app
    volumes:
      - ./back:/app
    ports:
      - "8091:8080"
    command: sh -c "./mvnw clean install && java -jar target/*.jar"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    restart: unless-stopped
